### ISSUE TITLE
Working version?

### ISSUE THREAD

**Issue by juliocbcotta** [steffandroid/DaggerStackOverflowExample#1]
Hi, 
would you please update this sample (or create a branch) with a working sample? I would like to try the Dagger rc versions, but there is a lack of docs and samples and it would help a lot.
Thanks in advance.

**Comment by steffandroid** [comment]
Sure, Ron Shapiro pointed out that I had a cycle between my Module and Component (see https://github.com/google/dagger/issues/613#issuecomment-284807933), so I have removed that in commit https://github.com/steffandroid/DaggerStackOverflowExample/commit/e42f8abc7319c3ba40d48f10c53edf3d66a6ba72.
